/// <reference types="cypress" />
describe('E2E test that tests the form with data that will result in errors', () => {
  it('should visit', () => {
    cy.visit('/')
    cy.wait(500)
    cy.get('[data-cy=cardContainer]')
      .invoke('attr', 'class')
      .should('not.contain', 'flipped')
    cy.wait(500)
    cy.get('[data-cy=input-cardNumber]').type('1111 1111 1111 1111')
    cy.wait(500)
    cy.get('[data-cy=input-cardName]').type('Viktor Puke')
    cy.wait(500)
    cy.get('[data-cy=select-cardMonth]').select('03')
    cy.wait(500)
    cy.get('[data-cy=select-cardYear]').select('2024')
    cy.wait(500)
    cy.get('[data-cy=input-cardCVV]').type('13')
    cy.get('[data-cy=cardContainer]')
      .invoke('attr', 'class')
      .should('contain', 'flipped')
    cy.wait(2000)
    cy.get('[data-cy=submit]').click()
    cy.get('[data-cy=error-cardNumber]')
      .should('exist')
      .and('have.text', 'Invalid card number')
    cy.get('[data-cy=error-cardMonth]')
      .should('exist')
      .and('have.text', 'Expired card')
    cy.get('[data-cy=error-cardCVV]')
      .should('exist')
      .and('have.text', 'CVV must be 3 or 4 digits')
  })
})
